use crate::state::{Card, Suit};

pub const fn init_deck() -> [Card; 52] {
    // compile time initialization of deck
    [
        Card {
            suit: Suit::Spades,
            rank: 2,
            chip_val: 2,
            edition: None,
            enhancements: None,
            seal: None,
        },
        Card {
            suit: Suit::Spades,
            rank: 3,
            chip_val: 3,
            edition: None,
            enhancements: None,
            seal: None,
        },
        Card {
            suit: Suit::Spades,
            rank: 4,
            chip_val: 4,
            edition: None,
            enhancements: None,
            seal: None,
        },
        Card {
            suit: Suit::Spades,
            rank: 5,
            chip_val: 5,
            edition: None,
            enhancements: None,
            seal: None,
        },
        Card {
            suit: Suit::Spades,
            rank: 6,
            chip_val: 6,
            edition: None,
            enhancements: None,
            seal: None,
        },
        Card {
            suit: Suit::Spades,
            rank: 7,
            chip_val: 7,
            edition: None,
            enhancements: None,
            seal: None,
        },
        Card {
            suit: Suit::Spades,
            rank: 8,
            chip_val: 8,
            edition: None,
            enhancements: None,
            seal: None,
        },
        Card {
            suit: Suit::Spades,
            rank: 9,
            chip_val: 9,
            edition: None,
            enhancements: None,
            seal: None,
        },
        Card {
            suit: Suit::Spades,
            rank: 10,
            chip_val: 10,
            edition: None,
            enhancements: None,
            seal: None,
        },
        Card {
            suit: Suit::Spades,
            rank: 11,
            chip_val: 10,
            edition: None,
            enhancements: None,
            seal: None,
        },
        Card {
            suit: Suit::Spades,
            rank: 12,
            chip_val: 10,
            edition: None,
            enhancements: None,
            seal: None,
        },
        Card {
            suit: Suit::Spades,
            rank: 13,
            chip_val: 10,
            edition: None,
            enhancements: None,
            seal: None,
        },
        Card {
            suit: Suit::Spades,
            rank: 14,
            chip_val: 11,
            edition: None,
            enhancements: None,
            seal: None,
        },
        Card {
            suit: Suit::Hearts,
            rank: 2,
            chip_val: 2,
            edition: None,
            enhancements: None,
            seal: None,
        },
        Card {
            suit: Suit::Hearts,
            rank: 3,
            chip_val: 3,
            edition: None,
            enhancements: None,
            seal: None,
        },
        Card {
            suit: Suit::Hearts,
            rank: 4,
            chip_val: 4,
            edition: None,
            enhancements: None,
            seal: None,
        },
        Card {
            suit: Suit::Hearts,
            rank: 5,
            chip_val: 5,
            edition: None,
            enhancements: None,
            seal: None,
        },
        Card {
            suit: Suit::Hearts,
            rank: 6,
            chip_val: 6,
            edition: None,
            enhancements: None,
            seal: None,
        },
        Card {
            suit: Suit::Hearts,
            rank: 7,
            chip_val: 7,
            edition: None,
            enhancements: None,
            seal: None,
        },
        Card {
            suit: Suit::Hearts,
            rank: 8,
            chip_val: 8,
            edition: None,
            enhancements: None,
            seal: None,
        },
        Card {
            suit: Suit::Hearts,
            rank: 9,
            chip_val: 9,
            edition: None,
            enhancements: None,
            seal: None,
        },
        Card {
            suit: Suit::Hearts,
            rank: 10,
            chip_val: 10,
            edition: None,
            enhancements: None,
            seal: None,
        },
        Card {
            suit: Suit::Hearts,
            rank: 11,
            chip_val: 10,
            edition: None,
            enhancements: None,
            seal: None,
        },
        Card {
            suit: Suit::Hearts,
            rank: 12,
            chip_val: 10,
            edition: None,
            enhancements: None,
            seal: None,
        },
        Card {
            suit: Suit::Hearts,
            rank: 13,
            chip_val: 10,
            edition: None,
            enhancements: None,
            seal: None,
        },
        Card {
            suit: Suit::Hearts,
            rank: 14,
            chip_val: 11,
            edition: None,
            enhancements: None,
            seal: None,
        },
        Card {
            suit: Suit::Diamonds,
            rank: 2,
            chip_val: 2,
            edition: None,
            enhancements: None,
            seal: None,
        },
        Card {
            suit: Suit::Diamonds,
            rank: 3,
            chip_val: 3,
            edition: None,
            enhancements: None,
            seal: None,
        },
        Card {
            suit: Suit::Diamonds,
            rank: 4,
            chip_val: 4,
            edition: None,
            enhancements: None,
            seal: None,
        },
        Card {
            suit: Suit::Diamonds,
            rank: 5,
            chip_val: 5,
            edition: None,
            enhancements: None,
            seal: None,
        },
        Card {
            suit: Suit::Diamonds,
            rank: 6,
            chip_val: 6,
            edition: None,
            enhancements: None,
            seal: None,
        },
        Card {
            suit: Suit::Diamonds,
            rank: 7,
            chip_val: 7,
            edition: None,
            enhancements: None,
            seal: None,
        },
        Card {
            suit: Suit::Diamonds,
            rank: 8,
            chip_val: 8,
            edition: None,
            enhancements: None,
            seal: None,
        },
        Card {
            suit: Suit::Diamonds,
            rank: 9,
            chip_val: 9,
            edition: None,
            enhancements: None,
            seal: None,
        },
        Card {
            suit: Suit::Diamonds,
            rank: 10,
            chip_val: 10,
            edition: None,
            enhancements: None,
            seal: None,
        },
        Card {
            suit: Suit::Diamonds,
            rank: 11,
            chip_val: 10,
            edition: None,
            enhancements: None,
            seal: None,
        },
        Card {
            suit: Suit::Diamonds,
            rank: 12,
            chip_val: 10,
            edition: None,
            enhancements: None,
            seal: None,
        },
        Card {
            suit: Suit::Diamonds,
            rank: 13,
            chip_val: 10,
            edition: None,
            enhancements: None,
            seal: None,
        },
        Card {
            suit: Suit::Diamonds,
            rank: 14,
            chip_val: 11,
            edition: None,
            enhancements: None,
            seal: None,
        },
        Card {
            suit: Suit::Clubs,
            rank: 2,
            chip_val: 2,
            edition: None,
            enhancements: None,
            seal: None,
        },
        Card {
            suit: Suit::Clubs,
            rank: 3,
            chip_val: 3,
            edition: None,
            enhancements: None,
            seal: None,
        },
        Card {
            suit: Suit::Clubs,
            rank: 4,
            chip_val: 4,
            edition: None,
            enhancements: None,
            seal: None,
        },
        Card {
            suit: Suit::Clubs,
            rank: 5,
            chip_val: 5,
            edition: None,
            enhancements: None,
            seal: None,
        },
        Card {
            suit: Suit::Clubs,
            rank: 6,
            chip_val: 6,
            edition: None,
            enhancements: None,
            seal: None,
        },
        Card {
            suit: Suit::Clubs,
            rank: 7,
            chip_val: 7,
            edition: None,
            enhancements: None,
            seal: None,
        },
        Card {
            suit: Suit::Clubs,
            rank: 8,
            chip_val: 8,
            edition: None,
            enhancements: None,
            seal: None,
        },
        Card {
            suit: Suit::Clubs,
            rank: 9,
            chip_val: 9,
            edition: None,
            enhancements: None,
            seal: None,
        },
        Card {
            suit: Suit::Clubs,
            rank: 10,
            chip_val: 10,
            edition: None,
            enhancements: None,
            seal: None,
        },
        Card {
            suit: Suit::Clubs,
            rank: 11,
            chip_val: 10,
            edition: None,
            enhancements: None,
            seal: None,
        },
        Card {
            suit: Suit::Clubs,
            rank: 12,
            chip_val: 10,
            edition: None,
            enhancements: None,
            seal: None,
        },
        Card {
            suit: Suit::Clubs,
            rank: 13,
            chip_val: 10,
            edition: None,
            enhancements: None,
            seal: None,
        },
        Card {
            suit: Suit::Clubs,
            rank: 14,
            chip_val: 11,
            edition: None,
            enhancements: None,
            seal: None,
        },
    ]
}